# permissions for end users to edit exporterscraperconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: exporterscraperconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-exporter
    app.kubernetes.io/part-of: operator-exporter
    app.kubernetes.io/managed-by: kustomize
  name: exporterscraperconfig-editor-role
rules:
- apiGroups:
  - finops.krateo.io
  resources:
  - exporterscraperconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - finops.krateo.io
  resources:
  - exporterscraperconfigs/status
  verbs:
  - get
